### ISSUE TITLE
Question: Is zlux-file-explorer the same as IBM Explorer for z/OS Atlas?

### ISSUE THREAD

**Issue by lilcubby** [zowe/zlux-file-explorer#3]
Wondering what the relationship is between the zlux-file-explorer and IBM Explorer for z/OS Atlas is?Related question - is the web client in zlux-file-explorer a sample only? Can that sample be run outside of MVD?

**Comment by jplinardon** [comment]
The zlux-file-explorer and IBM Explorer for z/OS Atlas are distinct and use different code.

The web client in zlux-file-explorer is a sample only at this time. Although it could be reused by other application, it is not considered part of a control library and there will be different implementations of file browsers. The File Transfer Application and the code editor both have different file browsers. Unification work has not started yet.

Running the sample outside of MVD is not an exercise we have undertaken.

**Comment by lilcubby** [comment]
Thank you.

**Comment by DivergentEuropeans** [comment]
Hey @lilcubby 

If you are still interested in the File Explorer, an update as of 7/19/2019
It is the main directory viewing widget being used in the Editor (zlux-editor) and soon to be used in the File Transfer App (file-transfer-app). I can offer more info upon request! Main changes to come are the addition of themes.
